import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docusaurusTutorial: [{ type: 'autogenerated', dirName: 'docusaurus-tutorial' }],
  others: [{ type: 'autogenerated', dirName: 'others' }],
};

export default sidebars;