import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docusaurusTutorial: [{type: 'autogenerated',dirName: 'docusaurus-tutorial'}],
};

export default sidebars;